# Generated by Django 5.2.2 on 2025-06-07 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Age (yrs)')),
                ('weight', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight (Kg)')),
                ('height', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Height (Cm)')),
                ('bmi', models.FloatField(blank=True, null=True, verbose_name='BMI')),
                ('blood_group', models.IntegerField(blank=True, choices=[(11, 'A+'), (12, 'A-'), (13, 'B+'), (14, 'B-'), (15, 'O+'), (16, 'O-'), (17, 'AB+'), (18, 'AB-')], null=True, verbose_name='Blood Group')),
                ('pulse_rate', models.IntegerField(blank=True, null=True, verbose_name='Pulse rate (bpm)')),
                ('rr', models.IntegerField(blank=True, null=True, verbose_name='RR (breaths/min)')),
                ('hb', models.FloatField(blank=True, null=True, verbose_name='Hb (g/dl)')),
                ('cycle', models.IntegerField(blank=True, null=True, verbose_name='Cycle (R/I)')),
                ('cycle_length', models.IntegerField(blank=True, null=True, verbose_name='Cycle length (days)')),
                ('marriage_status_years', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Marriage Status (Yrs)')),
                ('pregnant', models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], null=True, verbose_name='Pregnant (Y/N)')),
                ('num_abortions', models.IntegerField(blank=True, null=True, verbose_name='No. of abortions')),
                ('beta_hcg_1', models.FloatField(blank=True, null=True, verbose_name='I beta-HCG (mIU/mL)')),
                ('beta_hcg_2', models.FloatField(blank=True, null=True, verbose_name='II beta-HCG (mIU/mL)')),
                ('fsh', models.FloatField(blank=True, null=True, verbose_name='FSH (mIU/mL)')),
                ('lh', models.FloatField(blank=True, null=True, verbose_name='LH (mIU/mL)')),
                ('fsh_lh_ratio', models.FloatField(blank=True, null=True, verbose_name='FSH/LH')),
                ('hip', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hip (inch)')),
                ('waist', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Waist (inch)')),
                ('waist_hip_ratio', models.FloatField(blank=True, null=True, verbose_name='Waist:Hip Ratio')),
                ('tsh', models.FloatField(blank=True, null=True, verbose_name='TSH (mIU/L)')),
                ('amh', models.FloatField(blank=True, null=True, verbose_name='AMH (ng/mL)')),
                ('prl', models.FloatField(blank=True, null=True, verbose_name='PRL (ng/mL)')),
                ('vit_d3', models.FloatField(blank=True, null=True, verbose_name='Vit D3 (ng/mL)')),
                ('prg', models.FloatField(blank=True, null=True, verbose_name='PRG (ng/mL)')),
                ('rbs', models.FloatField(blank=True, null=True, verbose_name='RBS (mg/dl)')),
                ('weight_gain', models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], null=True, verbose_name='Weight gain (Y/N)')),
                ('hair_growth', models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], null=True, verbose_name='Hair growth (Y/N)')),
                ('skin_darkening', models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], null=True, verbose_name='Skin darkening (Y/N)')),
                ('hair_loss', models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], null=True, verbose_name='Hair loss (Y/N)')),
                ('pimples', models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], null=True, verbose_name='Pimples (Y/N)')),
                ('fast_food', models.FloatField(blank=True, choices=[(1, 'Yes'), (0, 'No')], null=True, verbose_name='Fast food (Y/N)')),
                ('regular_exercise', models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], null=True, verbose_name='Regular Exercise (Y/N)')),
                ('bp_systolic', models.IntegerField(blank=True, null=True, verbose_name='BP Systolic (mmHg)')),
                ('bp_diastolic', models.IntegerField(blank=True, null=True, verbose_name='BP Diastolic (mmHg)')),
                ('follicle_no_l', models.IntegerField(blank=True, null=True, verbose_name='Follicle No. (L)')),
                ('follicle_no_r', models.IntegerField(blank=True, null=True, verbose_name='Follicle No. (R)')),
                ('avg_f_size_l', models.FloatField(blank=True, null=True, verbose_name='Avg. F size (L) (mm)')),
                ('avg_f_size_r', models.FloatField(blank=True, null=True, verbose_name='Avg. F size (R) (mm)')),
                ('endometrium', models.FloatField(blank=True, null=True, verbose_name='Endometrium (mm)')),
            ],
        ),
    ]
