# Generated by Django 5.2.2 on 2025-06-07 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Age (yrs)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='blood_group',
            field=models.IntegerField(choices=[(11, 'A+'), (12, 'A-'), (13, 'B+'), (14, 'B-'), (15, 'O+'), (16, 'O-'), (17, 'AB+'), (18, 'AB-')], verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='bmi',
            field=models.FloatField(verbose_name='BMI'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='bp_diastolic',
            field=models.IntegerField(verbose_name='BP Diastolic (mmHg)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='bp_systolic',
            field=models.IntegerField(verbose_name='BP Systolic (mmHg)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='cycle',
            field=models.IntegerField(verbose_name='Cycle (R/I)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='cycle_length',
            field=models.IntegerField(verbose_name='Cycle length (days)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='fast_food',
            field=models.FloatField(choices=[(1, 'Yes'), (0, 'No')], verbose_name='Fast food (Y/N)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='hair_growth',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], verbose_name='Hair growth (Y/N)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='hair_loss',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], verbose_name='Hair loss (Y/N)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Height (Cm)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='hip',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hip (inch)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='num_abortions',
            field=models.IntegerField(verbose_name='No. of abortions'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='pimples',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], verbose_name='Pimples (Y/N)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='pregnant',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], verbose_name='Pregnant (Y/N)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='pulse_rate',
            field=models.IntegerField(verbose_name='Pulse rate (bpm)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='regular_exercise',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], verbose_name='Regular Exercise (Y/N)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='rr',
            field=models.IntegerField(verbose_name='RR (breaths/min)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='skin_darkening',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], verbose_name='Skin darkening (Y/N)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='waist',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Waist (inch)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='waist_hip_ratio',
            field=models.FloatField(verbose_name='Waist:Hip Ratio'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight (Kg)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='weight_gain',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], verbose_name='Weight gain (Y/N)'),
        ),
    ]
