# Generated by Django 5.2.2 on 2025-06-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_make23mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='cycle',
            field=models.IntegerField(choices=[(2, 'Regular'), (4, 'Irregular')], verbose_name='Cycle (R/I)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='hair_growth',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], verbose_name='Body hair growth (Y/N)'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='hb',
            field=models.FloatField(blank=True, null=True, verbose_name='Hemoglobin (g/dl)'),
        ),
    ]
